repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: detect-private-key
      - id: fix-byte-order-marker

  - repo: local
    hooks:
      - id: swiftformat
        name: SwiftFormat
        entry: swiftformat
        language: system
        types: [swift]
        args: [--config, .swiftformat]

      - id: swiftlint
        name: SwiftLint
        entry: swiftlint
        language: system
        types: [swift]
        args: [lint, --quiet]
