disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - identifier_name
  - trailing_comma
  - opening_brace
  - switch_case_alignment
  - redundant_optional_initialization
  - for_where
  - force_unwrapping
  - function_parameter_count

opt_in_rules:
  - empty_count
  - overridden_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - unused_import
  - vertical_whitespace

included:
  - Sources
  - Tests

excluded:
  - .build
  - .git
  - .swiftpm
  - Plugins

line_length:
  warning: 120
  error: 150

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20
