disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - identifier_name
  - trailing_comma
  - opening_brace
  - switch_case_alignment
  - redundant_optional_initialization
  - for_where
  - force_unwrapping
  - function_parameter_count

opt_in_rules:
  - empty_count
  - overridden_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - vertical_whitespace

analyzer_rules:
  - unused_import

included:
  - Sources
  - Plugins
  - Tests

excluded:
  - .build
  - .git
  - .swiftpm
