# This workflow builds and tests a Swift project using Swift Testing
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-15  # Use macOS 15 runner, which includes Xcode 16

    steps:
    - uses: actions/checkout@v4
      name: Checkout Repository

    - name: Select Xcode 16
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0'  # Specify Xcode 16.0 or later for Swift Testing

    - name: Verify Xcode Version
      run: xcodebuild -version

    - name: Verify Swift Version
      run: swift --version  # Should show Swift 6.0 or later

    - name: Build
      run: swift build -v

    - name: Run Tests
      run: swift test -v  # Runs Swift Testing tests
